### PR TITLE
this can be done via a zsh function

### PR DESCRIPTION
**Pull request by port19x**

### CODE REVIEW

**Comment by chmouel** [comment]
you maybe want to try it and see the difference compared to your snippet...

**Comment by port19x** [comment]
Meh, just checked out your code and yoinked the `-m` and bat preview

```sh
f() {
    "$@" "$(fzf -m --preview='bat --color=always {-1}')"
}
```

I don't find the `eza` preview valuable, so I omit that.

**Comment by port19x** [comment]
Also the other thing you link is different as well.
My snippet does cover the simple use case "I'm on the command line and want to fuzzy find file arguments".
Why not give the users who prefer minimal solutions an alternative in the readme?

**Comment by chmouel** [comment]
because that's probably not the goal of this repo to teach unix? what about showing to the world your snippet in a blog post? i'll make sure to read it and judge if it's "Meh" or not!

**Comment by chmouel** [comment]
(and fyi: the goal of this project is to insert the files of the current dir at the current prompt, not select and execute it)

**Pull request closed without merging**
